# Generated by Django 4.2.26 on 2025-11-28 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('interval_length', models.IntegerField(help_text='Length of interval in days, months, or years depending on your logic')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PROCESSING', 'Processing'), ('ERROR', 'Error'), ('FINISHED', 'Finished')], default='CREATED', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('region_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('distance_to_edge', models.FloatField()),
                ('study_type', models.CharField(max_length=255)),
                ('is_timeseries', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
