# Generated by Django 4.2.26 on 2026-02-14 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LULCStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('parsed_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lulc_studies', to='queries.parsedrequest')),
            ],
        ),
        migrations.CreateModel(
            name='LULCConclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics_json', models.JSONField(blank=True, null=True)),
                ('conclusion_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conclusion', to='lulc.lulcstudy')),
            ],
        ),
        migrations.CreateModel(
            name='LULCYearResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('image_path', models.TextField()),
                ('mask_path', models.TextField()),
                ('metrics_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='processing', max_length=20)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_results', to='lulc.lulcstudy')),
            ],
            options={
                'ordering': ['year'],
                'unique_together': {('study', 'year')},
            },
        ),
    ]
