# Generated by Django 4.2.26 on 2025-12-10 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeforestationRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('before_image_path', models.TextField(blank=True, null=True)),
                ('after_image_path', models.TextField(blank=True, null=True)),
                ('mask_path', models.TextField(blank=True, null=True)),
                ('mask_colormap_path', models.TextField(blank=True, null=True)),
                ('metrics_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=100, null=True)),
                ('parsed_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deforestation_result', to='queries.parsedrequest')),
            ],
        ),
    ]
